config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }	
	root to: "messages#index"
	resources :messages, only: [:create, :new, :index]

end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :sender, class_name: 'User'
	has_many :recipients
	has_many :users, :through => :recipients

	validates :sender_id, presence: true
	validates :body, presence: true

	def user_tokens=(ids)
		self.user_ids = ids
	end
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
	belongs_to :message
	belongs_to :user

	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :messages, foreign_key: :sender_id

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!

	def index
		@recipients = Recipient.where(user_id: current_user.id).order('created_at DESC')
	end

	def new
		@message = Message.new		
		@recipients = User.all
	end

	def create
		@message = current_user.messages.build(message_params)
		@recipients = User.all
		if @message.save
			flash[:success] = "Message Sent!"
			redirect_to	root_path 
		else
			flash.now[:error] = "Great Scott!"
			render :new 
		end
	end

	private
	def message_params
		params.require(:messages).permit(:body, :user_tokens => [])
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def root
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "success", error: "danger", alert: "warning", notice: "info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert alert-#{bootstrap_class_for(msg_type.to_sym)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
  
	def bootstrap_devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-block devise-bs">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h5>#{sentence}</h5>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="navbar-header"> 
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			<span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
		</button>
		<div class="navbar-brand"><%= link_to "Snap Message", root_path %></div>
	</div>
						
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav navbar-right">
			<% if user_signed_in? %>
				<li class="nav-link"><%= link_to "New", new_message_path %></li>
				<li class="nav-link"><%= link_to "Inbox", messages_path %></li>
				<li class="nav-link"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
			<% else %>
				<li class="nav-link"><%= link_to "Sign In", new_user_session_path %></li>
				<li class="nav-link"><%= link_to "Register", new_user_registration_path %></li>
			<% end %>
		</ul>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageRoom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="col-md-6 col-md-offset-3">
				<%= flash_messages %>
			</div>
		<%= yield %>
		</div>
	</div>
</div>

</body>
</html>

app/views/messages/_recipients.html.erb
<div class="col-md-6 col-md-offset-3">
	<%= form_for :messages, url: messages_path, html: { class: "well" } do |f| %>
		
		<div class="form-group">
			<%= f.text_area :body, placeholder: 'Type Your Message...', class: 'form-control', rows: 5 %>
		</div>
		
		<ul class="list-group form-group">
			<% @recipients.each do |user| %>
				<label for="user<%= user.id %>">
					<li class="list-group-item">
						<span><%= user.username %></span>
						<%= check_box_tag "messages[user_tokens][]", user.id, false, id: "user#{user.id}" %>
					</li>		
				</label>
			<% end %>
		</ul>
	
		<div id="form-group">
			<%= f.submit "Submit", class: "btn btn-primary" %>
		</div>
	<% end %>
	
</div>

app/views/messages/index.html.erb
<div class="col-md-6 col-md-offset-3">
	<ul class="list-group">
		<% @recipients.each do |recipient| %>
			<li class="list-group-item">
				<strong>Message Body: </strong><%= recipient.message.body %>
				<br>
				<small>From <%= recipient.message.sender.username %> on <%= l recipient.created_at.to_date %></small>
			</li>
		<% end %>
	</ul>
</div>

app/views/messages/new.html.erb
<%= render 'shared/errors', obj: @message %>
<%= render 'messages/recipients' %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="col-md-6 col-md-offset-3">
		<div class="alert alert-danger">
			<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
			<div class="panel-heading">
				<h2 class="panel-title">
					<%= pluralize(obj.errors.count, "error") %>
					prohibited this article from being saved:
				</h2>
				<div class="panel-body">
					<ul>
						<% obj.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/static_pages/root.html.erb
<h1>Hello</h1>